### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by lucadonnoh** [FoxySeta/Unibo_00819_Programmazione#1]
aggiungerei un .gitignore per i file *.sln, *.vcxproj e *.vcxproj.filters in quanto file di configurazione inutili con il fine della repo

**Comment by foxyseta** [comment]
Il `.gitignore` che uso ora è stato generato in automatico dal mio VS a partire da [qui](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore): cancella solo cache, build, etc.
Condivido con il mio IDE la politica del "mi libero solo di quelle risorse che sono **davvero** superflue in una repo". Quelli che hai citato, invece, sono tutti file di configurazione: specificano informazioni vitali come lo standard C++ usato, i file presenti nelle directory ma esclusi dal progetto etc. Non usare le impostazioni corrette per alcuni di questi potrebbe addirittura precluderti la compilazione! Per esempio, il mio codice in c++11 è anche corretto in c++20? E se scegliessi di implementare un main diverso per ogni esercizio, a chi spetterebbe il compito di escluderli dal progetto tutti a parte uno prima del testing?

**Comment by lucadonnoh** [comment]
Quei file son specifici di Visual Studio, ma non servono su altri IDE in cui bastano i cpp e gli hpp. Per quanto riguarda la compilazione è meglio creare un makefile (ti verrà chiesto anche nei corsi). Non ti attaccare troppo a Visual Studio, prova a usare un editor normale come VS Code che ti servirà di più

**Comment by foxyseta** [comment]
> non servono su altri IDE in cui bastano i cpp e gli hpp
Io avrei detto "non sono compatibili" però ho capito il senso e sicuramente non ci tengo a fare una crociata pro-VS. Forse era più autismo perché a prescindere dall'IDE volevo usare il .gitignore ufficiale certificato Github. Compromesso: nelle repo dei progetti dell'uni li nascondo visto che non sono previsti dalle consegne e nei progetti personali li lascio. Ci sta?

**Comment by lucadonnoh** [comment]
sì!
